# Generated by Django 4.0.5 on 2022-06-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_signupinfo_delete_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignupInfo',
            new_name='UserInfo',
        ),
    ]
